apiVersion: v1
kind: Secret
metadata: 
  name: "dns-keys-{{.Release.Name}}"
  annotations:
    "helm.sh/hook": pre-install
data:
{{if .Values.svcAccountKeyFile}}
  service-account.json: {{ include .Values.svcAccountKeyFile | b64enc | replace "\n" "" | quote }}
{{else}}
  service-account.json: {{ .Values.svcAccountKey | b64enc | replace "\n" "" | quote }}
{{end}}