---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus
  name: prometheus
spec:
  ports:
    - name: prometheus
      nodePort: {{.Values.prometheus_node_port}}
      targetPort: {{.Values.prometheus_port}}
      port: {{.Values.prometheus_port}}
      protocol: TCP
    - name: pushgateway
      nodePort: {{.Values.pushgateway_node_port}}
      targetPort: {{.Values.pushgateway_port}}
      port: {{.Values.pushgateway_port}}
      protocol: TCP
  selector:
    name: prometheus
  sessionAffinity: None
  type: NodePort
