apiVersion: v1
kind: Service
metadata:
  name: {{template "fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Jenkins.Master.Component}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
    - port: {{.Values.Jenkins.Master.ServicePort}}
      name: http
      targetPort: {{.Values.Jenkins.Master.ContainerPort}}
    - port: {{.Values.Jenkins.Master.SlaveListenerPort}}
      targetPort: {{.Values.Jenkins.Master.SlaveListenerPort}}
      name: slavelistener
  selector:
    component: "{{.Release.Name}}-{{.Values.Jenkins.Master.Component}}"
  type: {{.Values.Jenkins.Master.ServiceType}}
