apiVersion: v1
data:
  proxy-connect-timeout: "{{ .Values.proxyConnectTimeout }}"
  proxy-read-timeout: "{{ .Values.proxyReadTimeout }}"
  proxy-send-imeout: "{{ .Values.proxySendTimeout }}"
  hsts-include-subdomains: "{{ .Values.hstsIncludeSubdomains }}"
  body-size: "{{ .Values.bodySize }}"
  server-name-hash-bucket-size: "{{ .Values.serverNameHashBucketSize }}"
kind: ConfigMap
metadata:
  name: nginx-ingress-controller