---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  labels:
    name: nginx-ingress-controller
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-nginx-ingress-controller"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  type: {{ .Values.serviceType }}
  clusterIP: {{ .Values.loadBalancerIP }}
  externalName: {{ .Values.externalName }}
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: nginx-ingress-controller