apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{.Values.name}}
  labels:
    app: log-app
spec:
  template:
    metadata:
      labels:
        k8s: {{.Values.k8s}}
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: {{.Values.fluentd_container_name}}
        image: {{.Values.fluentd_image}}
        resources:
          limits:
            memory: {{.Values.memory_limits}}
          requests:
            cpu: {{.Values.cpu_requests}}
            memory: {{.Values.memory_requests}}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      - name: {{.Values.sidecar_container_name}}
        image: {{.Values.logrotate_image}}
        env:
          - name: ALLAPPLICATIONLOGS
            value: '/var/log/containers'
        volumeMounts:
        - name: varlog
          mountPath: /var/log/
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
