apiVersion: v1
description: A Fluentd Helm chart for Kubernetes
name: central-fluentd
version: 0.1.0
keywords: [fluentd, logging]
home: http://www.fluentd.org/
maintainers:
 - name: Leah Petersen
   email: leahnpetersen@gmail.com