apiVersion: v1
kind: Service
metadata:
  name: dex-app
spec:
  type: NodePort
  ports:
  - name: dex-app
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: {{.Values.DexApp.NodePort}}
  selector:
    app: dex-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dex-app
  labels:
    app: dex-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dex-app
    spec:
      containers:
      - name: dex-app
        image: {{.Values.DexApp.Image}}:{{.Values.DexApp.ImageTag}}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80

        volumeMounts:
        - name: tls
          mountPath: /etc/dex/tls

        env:
        - name: DEX_ISSUER
          value: {{.Values.Dex.Issuer}}
        - name: DEX_CA
          value: /etc/dex/tls/tls.ca
        - name: DEX_CERT
          value: /etc/dex/tls/tls.cert
        - name: DEX_KEY
          value: /etc/dex/tls/tls.key
        - name: DEX_APP_LISTEN_ADDRESS
          value: http://0.0.0.0:80
        - name: DEX_APP_REDIRECT_URI
          value: {{.Values.DexApp.RedirectUri}}

      volumes:
      - name: tls
        secret:
          secretName: dex.tls
